### ISSUE TITLE
dies if requiring json

### ISSUE THREAD

**Issue by timoxley** [gcanti/flowcheck#12]
When requiring json the browserify transform throws:

```
FlowcheckError: /…/build.json: Parse Error: Line 2: Unexpected token : while parsing file: /…/build.json
```

Should probably filter out `.json` extension from being handled by transform.

e.g.

![image](https://cloud.githubusercontent.com/assets/43438/6079352/1de4ee86-ae3f-11e4-81fd-f2ee2bdacc02.png)

https://github.com/hughsk/envify/blob/4d9ec383f50c4fe33b07d4d3fedb33768979799c/custom.js#L11

**Comment by gcanti** [comment]
Hi, good suggestion, thanks!

**Comment by timoxley** [comment]
Great work, thanks! :+1: :+1:
