### ISSUE TITLE
can't handle missing semicolon after type definition

### ISSUE THREAD

**Issue by timoxley** [gcanti/flowcheck#13]
If there's no semicolon after a type definition, flowcheck generates invalid javascript.

Not sure if the semicolon is required for valid `flow`, but it doesn't cause any compile-time error other than when used with flowcheck's generated assertion code. 

Usually good practice to place a semicolon and/or newline before any generated code anyway, just in case.

```js
type Thing = {
  name: string;
}

function validThing(thing:Thing) : Thing {
  return thing
}
```

```
> browserify thing.js
SyntaxError: …/thing.js: Unexpected token (5:1)
  3  | type Thing = {
  4  |   name: string;
> 5  | }var Thing = _f.shape({name: _f.string});
     |  ^
  6  |
  7  | function validThing(thing:Thing) : Thing {_f.check(arguments, _f.arguments([Thing])); var ret = (function (thing) {
  8  |   return thing
    at raise (…/node_modules/6to5ify/node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:342:15)
```

**Comment by gcanti** [comment]
> Not sure if the semicolon is required for valid flow

Section 3.9 Type Aliases of TypeScript Language Specification says:

```
TypeAliasDeclaration:
  type Identifier = Type ;
```

So maybe it's a good thing to throw a syntax error

**Comment by timoxley** [comment]
sure, but that's a semi after the identifier, rather than whole declaration.

Looking at https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md I see lots of instances where   they omit a semi after the declaration:

https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#36-named-types
```js
interface EventObject {  
    x: number;  
    y: number;  
}

interface EventHandlers {  
    mousedown?: (event: EventObject) => void;  
    mouseup?: (event: EventObject) => void;  
    mousemove?: (event: EventObject) => void;  
}

function setEventHandlers(handlers: EventHandlers) { ... }
```
```js
interface Point { x: number; y: number; }

var a = { x: 0, y: <number> undefined };  
```
And it's not in the grammar as far as I can see https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#a-grammar

**Comment by gcanti** [comment]
> And it's not in the grammar as far as I can see

`interface` looks different from `type` alias: in section https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.9 I see

TypeAliasDeclaration:
   `type` Identifier `=` Type `;`

Some examples of type alias declarations (in the same section):

```
type StringOrNumber = string | number;  
type Text = string | { text: string };  
type Coordinates = [number, number];  
type NameLookup = Dictionary<string, Person>;  
type Callback = (data: string) => void;  
type RecFunc = () => RecFunc;  
type ObjectStatics = typeof Object;
```
