### ISSUE TITLE
optionally demote errors to warnings at runtime

### ISSUE THREAD

**Issue by timoxley** [gcanti/flowcheck#14]
It would be nice if there were a way to adjust the amount of control flowcheck gets. 
AFAIK, there's no easy way to disable a specific browserify transform only in production from `package.json` scripts.

Suggest using [envify](https://github.com/hughsk/envify) to control the behaviour of flowcheck for a build.

This would allow npm scripts to use environment variables to produce different builds like:

```
FLOWCHECK=error browserify # default
FLOWCHECK=warn browserify # console.warn only
FLOWCHECK=none browserify # do nothing, flowcheck is disabled. A no-op.
NODE_ENV=production browserify # disable flowcheck by default in production too.
NODE_ENV=production FLOWCHECK=error browserify # explicitly enable errors in production
NODE_ENV=production FLOWCHECK=warn browserify # explicitly enable errors in production
```
This wouldn't require changing the transform code, you'd just need to toggle around the value of `process.env.FLOWCHECK` in your runtime code to decide which course of action to take.

**Comment by timoxley** [comment]
Note this is exactly (in a roundabout way) how react controls its type assertions:

![image](https://cloud.githubusercontent.com/assets/43438/6080213/a8e72166-ae49-11e4-90ff-a346327668e7.png)


https://github.com/facebook/react/blob/2aeb8a2a6beb00617a4217f7f8284924fa2ad819/vendor/constants.js#L19-L31


![image](https://cloud.githubusercontent.com/assets/43438/6080267/6cfef196-ae4a-11e4-938a-7bce1869639f.png)

https://github.com/facebook/react/blob/2aeb8a2a6beb00617a4217f7f8284924fa2ad819/grunt/config/browserify.js#L54-L79

![image](https://cloud.githubusercontent.com/assets/43438/6080255/48e58ff4-ae4a-11e4-8245-a3e8942d01cf.png)

https://github.com/facebook/react/blob/2aeb8a2a6beb00617a4217f7f8284924fa2ad819/vendor/constants.js#L19-L31

**Comment by timoxley** [comment]
🎉

**Comment by gcanti** [comment]
https://github.com/gcanti/flowcheck/issues/24
