### ISSUE TITLE
remove debugger

### ISSUE THREAD

**Issue by timoxley** [gcanti/flowcheck#15]
Please consider removing the `debugger` statement in the generated code. 

> If an assert fails the debugger kicks in so you can inspect the stack and quickly find out what's wrong.

I can see how this appears convenient but controlling when the debugger breaks and which errors it can ignore should be solely the responsibility of the application developer.

Forcing a `debugger` in there prevents the application developer from being able to control their own debugging environment. e.g. perhaps I want to ignore most of the throws, and set a conditional breakpoint to identify a particularly troublesome error; The current situation makes this very frustrating indeed  as one must to keep stepping over your `debugger` statement.

If the application developer wants to set a breakpoint at the line of the `throw` they can easily opt into this themselves using their own developer tools.

**Comment by gcanti** [comment]
> Please consider removing the debugger statement in the generated code

I could make the `assert.js` companion lib configurable (maybe it would solve #14 as well).
In particular you could decide the behaviour of the `assert` function when an assert fails.

To explain the present choice I'd say that a TypeError is really really bad, so I thought that `assert.js` should behave like a compiler (and the Flow type checker): **you can't ignore type errors, you must fix them**. What I forgot is a way to call the debugger only once (after a type error it's likely there will be other ones and it's annoying).

> perhaps I want to ignore most of the throws, and set a conditional breakpoint to identify a particularly troublesome error

May I ask you in which use case you'd be interested in ignoring (or getting just warnings as of #14) when a type error happens? It seems dangerous and contrary to the very purpose of this library since **a type error is, by definition, a bug**.

**Comment by timoxley** [comment]
Putting the `debugger` in there simply restricts exactly how users are able to debug, in fact it's made debugging certain scenarios absolutely impossible. Without the `debugger` I am free to use the debugging method of my choosing, with the `debugger` I am **forced** to manually step past hundreds of failures to get to the error in question.

> To explain the present choice I'd say that a TypeError is really really bad, so I thought that assert.js should behave like a compiler
> It seems dangerous and contrary to the very purpose of this library
> you can't ignore type errors, you must fix them

You can lead a horse to water… 
You've got some great tools with this and tcomb, just let these libraries do their one job of identifying type issues and allow the developer the freedom to choose how they handle that information. The best tools are those which can be used/abused in ways the original author did not envision.

**Comment by timoxley** [comment]
> you must fix them

this is what you're saying by throwing. If I catch that then I'm saying "nah, I got this under control" but I can't make this decision (when devtools is open) with the debugger statement in there.

> May I ask you in which use case you'd be interested in ignoring (or getting just warnings 

when i'm validating external input such as API responses or user input, I'd like to be able to use my own error handler to bundle errors up and display a friendly message to the user, but this is a real pain in the ass if I have developer tools open.

**Comment by gcanti** [comment]
> when i'm validating external input such as API responses or user input

I see. I think asserts and validations are two different things, for instance you can't use asserts in tcomb for doing input validation on a struct (or any type involving a struct). Every type in flowcheck has a `validate` method, specifically for doing input validation.

Anyway, what about customizing the failure behaviour (like tcomb https://github.com/gcanti/tcomb/issues/90)?

**Comment by timoxley** [comment]
> I think asserts and validations are two different things

Can you elaborate?

> for instance you can't use asserts in tcomb for doing input validation on a struct

Sure but since tcomb types are idempotent you can safely use the type constructor itself as the assert:

```js
function login(user) {
  // will noop if user already a User object
  // will throw if user does not validate against User struct
  user = new User(user)
  // … 
}
```

> Every type in flowcheck has a validate method, specifically for doing input validation.

Perhaps tcomb should have something similar for good measure.

**Comment by gcanti** [comment]
> Can you elaborate?

Sure, it was a little bit cryptic. What I mean is that asserts should answer the question: "**is** this value of this type"?

```js
function MyClass(name, age) {
  this.name = name; // string
  this.age = age; // number
}

MyClass.is = function (x) {
  // fast implementation
  return x instanceof MyClass;
};
```

ergo, in general, asserts are not suitable for input validation.

Validations should answer the question: "can this value **become** an instance of this type"?

```js
// this doesn't work
function validate(candidate, type) {
  return type.is(candidate);
}

validate({name: 'Giulio', age: 41}, MyClass); // => false
```

A good implementation of `validate` would be a function with the following signature:

```
(x: any) => Array<Error>
```

for example

```js
MyClass.validate = function (x) {
  // pseudo code
  var errors
  if x is not an object return error
  if x.name is not a string push error
  if x.age is not a number push error
  return errors;
};

MyClass.validate({name: 'Giulio', age: 41}); // => [] i.e. validation ok
```

**Comment by gcanti** [comment]
Same as tcomb, I will remove the `debugger` statement, thanks for taking the time to convince me ;-)

**Comment by iam4x** [comment]
Thank's :+1:
