### ISSUE TITLE
Alternative parser/transformer

### ISSUE THREAD

**Issue by Chrisui** [gcanti/flowcheck#18]
jstransform is great but has a limited set of features it supports out of the box (I think facebook are also moving their efforts away from it to other solutions) so for the sake of supporting a wider range of codebases it might be worth using a different library for transforming the code initially to run flowcheck. 

Ie. maybe acorn would be best? Seems babel (probably the transpiler in terms of lang coverage) uses a fork of this

For an example of one of my issues: flowcheck, sadly, falls down on destructuring parameters

```
function test({silent = true} = {}) {
  
}
```

**Comment by gcanti** [comment]
> I think facebook are also moving their efforts away from it to other solutions

It's not that clear at the moment https://github.com/facebook/jstransform/issues/73

Flowcheck was my first attempt to write a transformer: I found jstransform the easiest library to get the job done.

There is also recast https://github.com/benjamn/recast and I'm looking forward for a standard way for writing transformations targeting babel. https://github.com/babel/babel/issues/883 (Transformer API)

**Comment by nelix** [comment]
Hopefully when babel/babel#987 happens you could leverage babel?

**Comment by gcanti** [comment]
@nelix  :+1:

**Comment by deepsweet** [comment]
solution for webpack + flowcheck-loader + babel-loader: `babel?whitelist[]=flow!flowcheck!babel?blacklist[]=flow` loaders chain

**Comment by deepsweet** [comment]
it's time to try Babel Plugin API http://babeljs.io/docs/usage/plugins/ :wink:

**Comment by deepsweet** [comment]
+ https://github.com/babel/babel/blob/master/src/babel/transformation/transformers/other/flow.js for the reference

**Comment by gcanti** [comment]
FYI, this is an interesting experiment:

https://github.com/codemix/babel-plugin-typecheck

**Comment by gcanti** [comment]
FYI this is a first try with a babel plugin https://github.com/gcanti/babel-plugin-tcomb
I'd love to hear what you think, cheers
Giulio

**Comment by Chrisui** [comment]
Looks really interesting! Haven't got any immediate time to try it out but will be having a good look at some stronger typing soon at work hopefully.

I suppose we'd lose the ability to do static checks as a build step with the tcomb plugin?

**Comment by gcanti** [comment]
FYI I updated my babel plugin in order to support Flow type annotations: https://github.com/gcanti/babel-plugin-tcomb
