### ISSUE TITLE
Fails to work with ES Stage 1 decorator syntax

### ISSUE THREAD

**Issue by bebraw** [gcanti/flowcheck#19]
I am currently using flowcheck through webpack during development.

Here's the loader definition:

```javascript
    loaders: [
      {
        test: /\.jsx?$/,
        loaders: ['react-hot', 'babel?stage=1', 'flowcheck'],
        include: path.join(ROOT_PATH, 'app'),
      }
    ]
```

The problem is that this fails with a simple decorator such as

```javascript
@configureDragDropContext(HTML5Backend)
export default class Notes extends React.Component {
```

That yields error

```
ERROR in ./app/components/Notes.jsx
Module build failed: Error: Parse Error: Line 8: Unexpected token ILLEGAL
...
```

The trace points at `jstransform`. My guess is that it simply doesn't support decorator syntax yet. Maybe it would be possible to leverage babel transform instead?

Related to #18.

**Comment by gcanti** [comment]
Hi @bebraw

yes flowcheck uses jstransform (v8.2.0). I could upgrade to its latest version (v10.1.0) but I'm afraid it won't be enough. I'd like to switch to babel and write a babel plugin, but currently the plugin APIs are marked as **Highly experimental**, this is a concern. 
Moreover, last time I checked its site, there wasn't good documentation on how to write a plugin so I have to dig into the codebase (maybe I missed some resources?)

**Comment by bebraw** [comment]
Yeah, I'm afraid babel might be a moving target for now. That could get painful to maintain until their APIs stabilize.

I think I figured out a workaround for my case:

```
loaders: ['react-hot', 'babel', 'flowcheck', 'babel?stage=0&blacklist=flow']
```

First I let babel process the features not supported by flowcheck yet. After that I hit the processed source with it and finally strip the checks. This will do for now I think.

**Comment by gcanti** [comment]
Great! Thanks for the hint.

**Comment by gcanti** [comment]
FYI, this is an interesting experiment:

https://github.com/codemix/babel-plugin-typecheck

**Comment by bebraw** [comment]
That looks promising!

**Comment by gajus** [comment]
> FYI, this is an interesting experiment:
> https://github.com/codemix/babel-plugin-typecheck

What advantages does this have over?

```
loaders: ['react-hot', 'babel', 'flowcheck', 'babel?stage=0&blacklist=flow']
```

**Comment by hung-phan** [comment]
Based on my understanding, they basically do the same thing. However, I seem to get `https://github.com/codemix/babel-plugin-typecheck` up and running easier. I got so frustrated with `loaders: ['react-hot', 'babel', 'flowcheck', 'babel?stage=0&blacklist=flow']` in production mode. I simply could not optimise and remove the overheads of flowcheck, even though I did try it many times. Correct me if I was wrong.

**Comment by bebraw** [comment]
@hung-phan Yeah, `babel-plugin-typecheck` seems like a very strong option! Looks like it has matured a lot.

**Comment by gcanti** [comment]
FYI this is a first try with a babel plugin https://github.com/gcanti/babel-plugin-tcomb
I'd love to hear what do you think, cheers
Giulio

**Comment by bebraw** [comment]
@gcanti On a quick look that seems very promising. I've been toying around with Flow static checker lately but it's a really involved approach. It's still maturing for sure and missing support for some newer language features.

If you are using Webpack, I think you can inject that `import t from 'tcomb';` through a plugin (global `t`). I'm not exactly sure if this is a good idea due to potential shadowing issues but at least that allows you to avoid adding the import everywhere in your code.

**Comment by gcanti** [comment]
Hi @bebraw
Thanks for your feedback.

> avoid adding the import everywhere in your code

- if you are using babel-plugin-tcomb it's likely you are already using tcomb so this shouldn't be much of a problem
- otherwise it should be possible to inject an import declaration if the plugin doesn't find tcomb in scope (*)

(*) in https://github.com/gcanti/babel-plugin-tcomb/blob/master/src/index.js#L168 something like

```js
if (!tcomb) {
  // automatically add import t from 'tcomb';
}
```

**Comment by bebraw** [comment]
@gcanti Ah, cool. Maybe you could push that behind an option. No strong opinion on this one.

**Comment by gcanti** [comment]
Hi @bebraw, 

FYI I updated my babel plugin in order to support Flow type annotations: https://github.com/gcanti/babel-plugin-tcomb and inject `import t from 'tcomb'` automatically as you suggested. Now you can run Flow and babel-plugin-tcomb side by side getting the best of 2 worlds: static and runtime type checking

**Comment by bebraw** [comment]
@gcanti Great. Would you like to cover tcomb at SurviveJS blog? I could set up a little interview. If you are interested, hit me through Twitter or email.

**Comment by gcanti** [comment]
@bebraw Sure, it would be great

**Comment by bebraw** [comment]
@gcanti Gotcha. I'll DM you details. Thanks. 👍
