### ISSUE TITLE
Support flow comment annotations

### ISSUE THREAD

**Issue by cesarandreu** [gcanti/flowcheck#22]
There's a babel plugin: [babel-plugin-flow-comments](https://github.com/babel-plugins/babel-plugin-flow-comments), which would make the webpack workflow a bit simpler. On top of that, it lets people use comments to annotate types, which is great for when you want type annotations but your syntax highlighter doesn't have full flow support (e.g. babel-sublime).

Would supporting comments be feasible?

**Comment by gcanti** [comment]
> Would supporting comments be feasible?

Hi,
I'd say no since the current implementation uses jstransform (which AFAIK doesn't support this kind of comment parsing).

**Comment by benjamingr** [comment]
I'm also interested in this feature, I think a transform from comments to type annotations would make this transformation fairly possible.
