### ISSUE TITLE
FYI: I’m no longer maintaining flowcheck-loader

### ISSUE THREAD

**Issue by gaearon** [gcanti/flowcheck#23]
Since I don’t use it, I’m no longer maintaining https://github.com/gaearon/flowcheck-loader. @gcanti I requested a transfer of the repo to you, and I have also added you as an owner on npm. Thank you for your work!

**Comment by gcanti** [comment]
Hi @gaearon, thanks for writing and maintaining `flowcheck-loader`. FYI I don't use it as well, do you still want me to accept the transfer? (if that’s the case there's no problem for me)

**Comment by gaearon** [comment]
Yeah, please do, if that’s not difficult. I’m just trying to clean up my old repos and make it clear which ones I don’t plan to maintain at all.

**Comment by gcanti** [comment]
Ok. Could you please renew the transfer request? The old one seems expired

**Comment by gaearon** [comment]
Done

**Comment by gaearon** [comment]
Thanks!

**Comment by gcanti** [comment]
Accepted, thanks.

Cheers,
Giulio
