### ISSUE TITLE
Check type at re-assigment

### ISSUE THREAD

**Issue by phadej** [gcanti/flowcheck#9]
```js
var n: number = 1
n = "foo"
```

transforms into:

```js
var n = f.check(1, f.number)
n = "foo"
```

which doesn't cause any (runtime) errors.

**Comment by gaearon** [comment]
+1

**Comment by gcanti** [comment]
it would be tricky (though very interesting!), flowcheck at the moment does a local source-to-source transformation, the only exception is type erasure in polymorphic classes where it climb up the declarations path looking for generics. Here we are speaking of a more advanced type analysis.
I'll dig into jstransform to see what it can be done.

relevant discussion:

https://github.com/6to5/6to5/issues/458
